# discover_client/config.toml


[[sources]]
source_id = "1"
source_type = "nmap"
enabled = true

[sources.settings]
scan_flags = "-sn -PR"
scan_interval_s = 300
target_subnet = ""

[[sources]]
source_id = "2"
source_type = "ssdp"
enabled = true

[sources.settings]
scan_interval_s = 60

[[sources]]
source_id = "3"
source_type = "mdns"
enabled = true

[sources.settings]
scan_interval_s = 30
service_types = []

[[sources]]
source_id = "4"
source_type = "mqtt"
enabled = true

[sources.settings]
host = "localhost"
password = ""
port = 1883
topic_blacklist = []
topic_whitelist = []
username = ""
